encoder:
  init_dim: 8  # initial dimension
  hid_dim: 128  # hidden dimension in the bottleneck
  # number of residual blocks between down-sampling blocks
  n_resnet_blocks: 2
  downsampling: 'time'    # 'time' 'freq'
  # lengths of the encoded (down-sampled) series
  downsampled_width:
    lf: 8
    hf: 32
    freq: 4  # same freq downsampling for lf and hf components
    combined: 32  # when lfhf_separation = False
  # number of neighbouring frequencies to be convoluted
  frequency_bandwidth: 3

# other settings of decoder are forced to be the
# same as encoder for consistency
decoder:
  # number of residual blocks between up-sampling blocks
  n_resnet_blocks: 2

### for STFT ###
# number of FFT points (frequency resolution)
n_fft: 8  # for efficient computation, use power of 2
stft_split_type: 'real_imag'  # 'real_imag' 'magnitude_phase'
lfhf_separation: true

VQ-VAE:
  # number of codewords
  codebook_sizes:
    lf: 64
    hf: 64
  codebook: {}
